### ISSUE TITLE
Update dependency to Tesstwo 8

### ISSUE THREAD

**Issue by mercuriete** [mercuriete/android-mrz-reader#1]
It seems there are new version of tesstwo.
https://bintray.com/rmtheis/maven/tess-two

**Comment by mercuriete** [comment]
branch created:

https://github.com/mercuriete/android-mrz-reader/tree/1-update-dependency-tesstwo-8

**Comment by mercuriete** [comment]
Changing to priority P1.
It seems to be an easy change.
We can try to use the new traineddata.

**Comment by supportreq** [comment]
is this updated?

**Comment by mercuriete** [comment]
@supportreq 
Sorry but I am trying to advance on that topic as fast as i can..

https://github.com/mercuriete/android-mrz-reader/blob/1-update-dependency-tesstwo-8/MRZReader/build.gradle#L30

in that line you can check the answer is no.

Thanks for your interest :)
