### ISSUE TITLE
How to speed up scan ? 

### ISSUE THREAD

**Issue by tahafarooqui** [mercuriete/android-mrz-reader#12]
Issue 1: It takes up to 10 seconds to scan and get MRZ.  How to speed up the process. 

Issue 2: How to activate ML -Kit ?

**Comment by mercuriete** [comment]
I am sorry, buy this project is a spare time project.

I can try to update in a few month to the latest dependencies.. but this doesn't mean It magically convert this application in real time.

Moreover this ticket is duplicated of #5 

In this repository somebody has tried to reimplement the functionality using opencv.
you can check the conversation in #6


Im sorry for not helping you, but I am not longer working of law enforcement stuff anymore.

Thanks for try to use this repo 👍
