### ISSUE TITLE
PASSPORT_TD_3_LINE_2_REGEX bug

### ISSUE THREAD

**Issue by smithaaron** [mercuriete/android-mrz-reader#81]
The passport line 2 regex expects only a numeric character for the second last character of the MRZ. This is incorrect according to the [spec](https://en.wikipedia.org/wiki/Machine-readable_passport#Passport_booklets) (and my passport), which states "Check digit over digits 29–42 (may be < if all characters are <)". So the regex should be updated from
```java
public static final String PASSPORT_TD_3_LINE_2_REGEX = "([A-Z0-9<]{9})([0-9]{1})([A-Z]{3})([0-9]{6})([0-9]{1})([M|F|X|<]{1})([0-9]{6})([0-9]{1})([A-Z0-9<]{14})([0-9]{1})([0-9]{1})";
```
to
```java
public static final String PASSPORT_TD_3_LINE_2_REGEX = "([A-Z0-9<]{9})([0-9]{1})([A-Z]{3})([0-9]{6})([0-9]{1})([M|F|X|<]{1})([0-9]{6})([0-9]{1})([A-Z0-9<]{14})([0-9<]{1})([0-9]{1})";
```

**Comment by mercuriete** [comment]
I am using an external library for MRZ validation.
https://sourceforge.net/p/jmrtd/code/HEAD/tree/

I will check it but I think I can't do anything with that.

I will leave this issue open a little bit.

**Comment by smithaaron** [comment]
My apologies. I just realised I made a huge mistake.

I meant to post this bug on a completely different android MRZ project 🤦
https://github.com/alimertozdemir/EPassportNFCReader

**Comment by mercuriete** [comment]
@smithaaron 
No problem :)

**Comment by mercuriete** [comment]
@smithaaron 
maybe you want to check this repository
https://github.com/mercuriete/ajmrtd2

It is a simple NFC reader copied from the original ajmrtd project.
